create table category
(
    id              bigint generated by default as identity,
    name            varchar(255),
    ordering_number bigint,
    parent_id       bigint,
    primary key (id)
);

alter table category
    add constraint FK2y94svpmqttx80mshyny85wqr
        foreign key (parent_id)
            references category
